# # Docker
# # Build and push an image to Azure Container Registry
# # https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# trigger:
# - main

# resources:
# - repo: self

# variables:
#   # Container registry service connection established during pipeline creation
#   dockerRegistryServiceConnection: 'acba34a4-0ebc-442d-941f-8eb99adbf80e'
#   imageRepository: 'alabenachourappnodedevops'
#   containerRegistry: 'reactwebsite.azurecr.io'
#   dockerfilePath: '$(Build.SourcesDirectory)/backend/dockerfile'
#   tag: '$(Build.BuildId)'

#   # Agent VM image name
#   vmImageName: 'ubuntu-latest'

# stages:
# - stage: Build
#   displayName: Build and push stage
#   jobs:
#   - job: Build
#     displayName: Build
#     pool:
#       vmImage: $(vmImageName)
#     steps:
#     - task: Docker@2
#       displayName: Build and push an image to container registry
#       inputs:
#         command: buildAndPush
#         repository: $(imageRepository)
#         dockerfile: $(dockerfilePath)
#         containerRegistry: $(dockerRegistryServiceConnection)
#         tags: |
#           $(tag)
trigger:
  branches:
    include:
      - main  

resources:
  repositories:
    - repository: self  

variables:
  dockerRegistryServiceConnection: 'acba34a4-0ebc-442d-941f-8eb99adbf80e'
  containerRegistry: 'reactwebsite.azurecr.io'
  imageRepositoryBackend: 'alabenachourapp-backend'
  imageRepositoryFrontend: 'alabenachourapp-frontend'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
- stage: 
  displayName: Run Test cases using jest
  jobs:
    - job: Test
      displayName: Run Test Cases
      steps:
      - task: NodeTool@0
        inputs:
          versionSource: 'spec'
          versionSpec: '18.x'
      - task: Npm@1
        inputs:
          command: 'install'
          workingDir: 'frontend'
      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: 'test'
          workingDir: 'frontend'
- stage: Build
  displayName: Build and Push Stage
  jobs:
  - job: Build
    displayName: Build and Push Docker Images
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self

    # Docker login step
    - task: Docker@2
      displayName: 'Login to Azure Container Registry'
      inputs:
        command: 'login'
        containerRegistry: $(dockerRegistryServiceConnection)

    - task: DockerCompose@1
      displayName: Build Images with Docker Compose
      inputs:
        containerregistry: $(dockerRegistryServiceConnection)
        dockerComposeFile: '$(Build.SourcesDirectory)/docker-compose.yml'
        projectName: 'app-node-devops'
        action: 'Build services'
        addPipelineDataAsLabels: false
        tags: |
          $(tag)
          latest
      env:
        TAG: $(tag)

    - task: DockerCompose@1
      displayName: Push Images with Docker Compose
      inputs:
        containerregistry: $(dockerRegistryServiceConnection)
        dockerComposeFile: '$(Build.SourcesDirectory)/docker-compose.yml'
        projectName: 'app-node-devops'
        action: 'Push services'
      env:
        TAG: $(tag)
