
trigger:
  branches:
    include:
      - main  

resources:
  repositories:
    - repository: self  

variables:
  dockerRegistryServiceConnection: 'acba34a4-0ebc-442d-941f-8eb99adbf80e'
  containerRegistry: 'reactwebsite.azurecr.io'
  imageRepositoryBackend: 'alabenachourapp-backend'
  imageRepositoryFrontend: 'alabenachourapp-frontend'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'
  k8sNamespace: 'default'
  imagePullSecret: 'acr-secret'
  kubernetesServiceConnection: 'app-demo-app-demo-default-1732626995245'

stages:
- stage: RunTests
  displayName: Run Test Cases using Jest
  jobs:
    - job: Test
      displayName: Run Test Cases
      steps:
      - task: NodeTool@0
        inputs:
          versionSource: 'spec'
          versionSpec: '18.x'
        displayName: Set up Node.js
      - task: Npm@1
        inputs:
          command: 'install'
          workingDir: 'frontend'
        displayName: Install dependencies
      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: 'run test -- --watchAll=false'
          workingDir: 'frontend'
        displayName: Run Jest tests

- stage: Build
  displayName: Build and Push Stage
  jobs:
  - job: Build
    displayName: Build and Push Docker Images
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self

    # Docker login step
    - task: Docker@2
      displayName: 'Login to Azure Container Registry'
      inputs:
        command: 'login'
        containerRegistry: $(dockerRegistryServiceConnection)

    - task: DockerCompose@1
      displayName: Build Images with Docker Compose
      inputs:
        containerregistry: $(dockerRegistryServiceConnection)
        dockerComposeFile: '$(Build.SourcesDirectory)/docker-compose.yml'
        projectName: 'app-node-devops'
        action: 'Build services'
        addPipelineDataAsLabels: false
        tags: |
          $(tag)
          latest
      env:
        TAG: $(tag)

    - task: DockerCompose@1
      displayName: Push Images with Docker Compose
      inputs:
        containerregistry: $(dockerRegistryServiceConnection)
        dockerComposeFile: '$(Build.SourcesDirectory)/docker-compose.yml'
        projectName: 'app-node-devops'
        action: 'Push services'
      env:
        TAG: $(tag)

- stage: Deploy
  displayName: Deploy Stage
  dependsOn: Build
  jobs:
    - deployment: Deploy
      displayName: Deploy to Kubernetes
      pool:
        vmImage: $(vmImageName)
      environment: 'app-demo.default' 
      strategy:
        runOnce:
          deploy:
            steps:
            - task: KubernetesManifest@1
              displayName: Create imagePullSecret
              inputs:
                action: createSecret
                namespace: $(k8sNamespace)
                secretName: $(imagePullSecret)
                dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
                kubernetesServiceEndpoint: $(kubernetesServiceConnection)

            - task: KubernetesManifest@1
              displayName: Deploy to Kubernetes Cluster
              inputs:
                action: deploy
                namespace: $(k8sNamespace)
                manifests: |
                 $(Build.SourcesDirectory)/Kubernetes/deployment.yaml
                 $(Build.SourcesDirectory)/Kubernetes/service.yaml
                containers: |
                  $(containerRegistry)/$(imageRepositoryBackend):$(tag)
                  $(containerRegistry)/$(imageRepositoryFrontend):$(tag)
