apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  replicas: 2
  progressDeadlineSeconds: 1200
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-server
        image: reactwebsite.azurecr.io/alabenachourapp-backend:$(TAG)
        ports:
          - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: mongosecret
                key: MONGOCONNECTION
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
        

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: reactwebsite.azurecr.io/alabenachourapp-frontend:$(TAG)
        ports:
          - containerPort: 3000
