apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-server
        image: reactwebsite.azurecr.io/alabenachourapp-backend:$(TAG)  # Use the pipeline tag
        ports:
          - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGO_URL


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: reactwebsite.azurecr.io/alabenachourapp-frontend:$(TAG)  # Use the pipeline tag
        ports:
          - containerPort: 3000
